
clusters = source1, source2, source3, target

source1.bootstrap.servers = 192.168.1.21:9092
source2.bootstrap.servers = [IP_ADDRESS]
source3.bootstrap.servers = [IP_ADDRESS]

target.bootstrap.servers = kafka:29092

source1->target.enabled = true
source2->target.enabled = true
source3->target.enabled = true

source1->target.topics = .*
source2->target.topics = .*
source3->target.topics = .*

replication.policy.separator = .

tasks.max = 3
sync.topic.acls.enabled = false
emit.heartbeats.interval.seconds = 5
