# Telegraf Configuration for HPC Metrics Collection
''' 
This configuration file is designed to 
collect system metrics from a Windows client 
in a high-performance computing (HPC) environment 
and send them to a Kafka topic for further processing.
'''

# Label the metrics with global tags for cluster and node identification
[global_tags]
  cluster = "hpc-local-poc" # Which cluster?
  node_name = "windows-client-1" # Node name in this cluster


[agent]
  interval = "5s" # How often to collect metrics
  round_interval = true # Whether to round the collection interval
  metric_batch_size = 1000 # How many metrics to collect before sending to outputs
  metric_buffer_limit = 10000 # Maximum number of metrics to buffer before sending to outputs
  flush_interval = "5s" # How often to flush metrics to outputs

[[inputs.cpu]]
  percpu = true # Whether to report per-CPU metrics
  totalcpu = true # Whether to report total CPU metrics
  collect_cpu_time = false # Whether to collect CPU time metrics
  report_active = true # Whether to report active CPU metrics

[[inputs.mem]]
  # Memory metrics configuration

[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]

[[inputs.diskio]]
  # Disk I/O metrics configuration

[[inputs.net]]
  interfaces = ["eth0", "Wi-Fi"] # Network interfaces to monitor

[[outputs.kafka]]
  brokers = ["${KAFKA_BROKER}"]
  topic = "hpc-raw-metrics"
  data_format = "json"
  json_timestamp_units = "1ms"