[global_tags]
  cluster = "hpc-local-poc"
  node_name = "windows-client-1"

[agent]
  interval = "5s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  flush_interval = "5s"

[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = true

[[inputs.mem]]

[[inputs.diskio]]

[[inputs.net]]

[[outputs.kafka]]
  brokers = ["${KAFKA_BROKER}"]
  topic = "hpc-raw-metrics"
  data_format = "json"
