apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "iot-producer.fullname" . }}
  labels:
    app: {{ include "iot-producer.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "iot-producer.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "iot-producer.name" . }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: KAFKA_BROKER
              value: {{ .Values.kafka.broker | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
